alias a='source ~/.bashrc'
alias b=nano
alias qa='b ~/.bash_aliases'
alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'
alias cd.....='cd ../../../..'
alias ..=cd..
alias ...=cd...
alias ....=cd....
alias .....=cd.....
alias d=ls
alias dir='ls -al'
